version: '3.1'

services:
  postgres:
    image: postgres:11.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: padmin
      POSTGRES_DB: learning
